cat(file=stderr(), "load Shiny functions", "\n")
source("Shiny_Startup_v1.R")
source("Shiny_UpdateWidgets_v1.R")
source("Shiny_Observers_v1.R")
source("Shiny_Setup_v1.R")
source("Shiny_Filter_v1.R")
source("Shiny_Transform_v1.R")
source("Shiny_Stats_v1.R")
source("Shiny_Norm_v1.R")
source("Shiny_Impute_v1.R")
source("Shiny_Plots_v1.R")
source("Shiny_Preprocess_v1.R")
source("Shiny_File_v1.R")
source("Shiny_QC_v1.R")
source("Shiny_Hide_v1.R")
source("Shiny_Render_v1.R")
source("Shiny_Overview_v1.R")
source("Shiny_MotifX_v1.R")
source("Shiny_Wiki_v1.R")
source("Shiny_ViSEAGO_v1.R")
source("Shiny_Pathway_v1.R")
source("Shiny_String_v1.R")
source("Shiny_MailMerge_v1.R")
source("Shiny_TMTSPQC_v1.R")
source("Shiny_Interactive_v1.R")
source("Shiny_MVA_v1.R")
source("Shiny_Tables_v1.R")



